CarFactory.Admin/Controllers/SeoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Application.Services.Dto;
using Abp.Runtime.Validation;
using Abp.Web.Security.AntiForgery;
using CarFactory.Application.Seo;
using CarFactory.Application.Seo.Dtos;
using CarFactory.Application.Users;

namespace CarFactory.Admin.Controllers
{
    [RoutePrefix("admin")]
    public class SeoController : CarFactoryControllerBase
    {
        private readonly ISeoAppService _seoAppService;

        public SeoController(ISeoAppService seoAppService, IUserNavigationManager userNavigationManager)
            : base(userNavigationManager)
        {
            _seoAppService = seoAppService;
        }

        // GET: Seo
        public async  Task<ActionResult> Index()
        {
            var setting = await _seoAppService.GetDefaultSeoAsync();

            var userMenu = GetUserMenu(PageNames.Seo).Result;
            ViewBag.UserMenu = userMenu;


            return View(setting); 
        }

        [Route("seo/saveseo")]
        [HttpPost]
        [DisableValidation]
        public async Task<JsonResult> SaveSeo(SeoEditDto editDto)
        {
            CheckModelState();

            bool status = false;
            string message = "";

            try
            {
                var oldModel = await _seoAppService.GetDefaultSeoAsync();
                if (oldModel != null)
                {
                    editDto.Watermark = oldModel.Watermark;
                    editDto.WatermarkAble = oldModel.WatermarkAble;
                }
                await _seoAppService.CreateOrUpdateSeoAsync(new CreateOrUpdateSeoInput() {SeoEditDto = editDto});
                status = true;
            }
            catch (Exception e)
            {
                status = false;
                message = e.Message;
            }

            return Json(new {success = status, message = message});
        }

        [Route("seo/savewatermark")]
        [HttpPost]
        [DisableValidation]
        public async Task<JsonResult> SaveWatermark(SeoEditDto editDto)
        {
            
            CheckModelState();

            bool status = false;
            string message = "";

            try
            {
                var oldModel = await _seoAppService.GetDefaultSeoAsync();
                if (oldModel != null)
                {
                    editDto.SiteTitle = oldModel.SiteTitle;
                    editDto.SiteKeywords = oldModel.SiteKeywords;
                    editDto.SiteDescription = oldModel.SiteDescription;
                }
                await _seoAppService.CreateOrUpdateSeoAsync(new CreateOrUpdateSeoInput() { SeoEditDto = editDto });
                status = true;
            }
            catch (Exception e)
            {
                status = false;
                message = e.Message;
            }

            return Json(new { success = status, message = message });
        }

        [Route("seo/savebanner")]
        [HttpPost]
        [DisableValidation]
        //[DisableAbpAntiForgeryTokenValidation]
        public async Task<JsonResult> SaveBanner(int id = 0)
        {
            CheckModelState();

            bool status = false;
            string message = "";

            try
            {
                var oldModel = await _seoAppService.GetSeoByIdAsync(new EntityDto(id));
                var defaultModel = await _seoAppService.GetDefaultSeoAsync();
                if (defaultModel == null || defaultModel.Id == oldModel.Id)
                {
                    //await _seoAppService.CreateOrUpdateSeoAsync(new CreateOrUpdateSeoInput() {SeoEditDto = editDto});
                    status = true;
                }
                else
                {
                    status = false;
                    message = "Seo数据对象只可是唯一项，数据中有多余项";
                }
            }
            catch (Exception e)
            {
                status = false;
                message = e.Message;
            }

            return Json(new { success = status, message = message });
        }


    }
}

CarFactory.Admin/Views/Seo/Index.cshtml
@using System.Web.Optimization
@model CarFactory.Application.Seo.Dtos.SeoListDto
@{
    ViewBag.Title = "Index";
    ViewBag.PageName = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string checkState = Model != null ? (Model.WatermarkAble ? "checked" : "") : "";
}

@section PageLevelStylePlugins
{
    @Styles.Render("~/assets/global/profile/css")
}

@section BreadCrumb
{
    <li>
        <a href="javascript:void(0)">首页</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="javascript:void(0)">@ViewBag.PageName</a>
        <i class="fa fa-circle"></i>
    </li>
}

<div class="profile-content">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light ">
                <div class="portlet-title tabbable-line">
                    <div class="caption caption-md">
                        <i class="icon-globe theme-font hide"></i>
                        <span class="caption-subject font-blue-madison bold uppercase">网站SEO设置</span>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#tab_1_1" data-toggle="tab" aria-expanded="false">SEO设置</a>
                        </li>
                        <li class="">
                            <a href="#tab_1_2" data-toggle="tab" aria-expanded="false">水印设置</a>
                        </li>

                    </ul>
                </div>
                <div class="portlet-body">
                    <div class="tab-content">
                        <!-- PERSONAL INFO TAB -->
                        @Html.HiddenFor(s => s.Id)
                        <div class="tab-pane active" id="tab_1_1">
                            <form role="form" id="siteSettingForm" postUrl="/admin/seo/saveseo">
                                <div class="form-group">
                                    <label class="control-label">网站名称</label>
                                    @*                                    <input type="text" placeholder="填写网站名称" class="form-control">*@
                                    @Html.TextBoxFor(s => s.SiteTitle, new { placeholder = "填写网站名称", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label class="control-label">网站关键词</label>
                                    @*                                    <input type="text" placeholder="" class="form-control">*@
                                    @Html.TextBoxFor(s => s.SiteKeywords, new { placeholder = "填写网站关键词", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label class="control-label">网站描述</label>
                                    @*                                    <input type="text" placeholder="" class="form-control">*@
                                    @Html.TextAreaFor(s => s.SiteDescription, new { placeholder = "填写网站描述", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label class="control-label">ICP备案序号</label>
                                    @*                                    <input type="text" placeholder="" class="form-control">*@
                                    @Html.TextBoxFor(s => s.IcpNumber, new { placeholder = "填写ICP备案序号", @class = "form-control" })
                                </div>
                                <div class="margiv-top-10">
                                    <button type="submit" id="submitBtn" class="btn green">保存</button>
                                </div>
                            </form>
                        </div>
                        <!-- END PERSONAL INFO TAB -->
@*                        <!-- Upload Banner TAB -->*@
@*                        <div class="tab-pane " id="tab_1_2">*@
@*                            <div class="dropzone" id="uploadImgs">*@
@*                                @if (string.IsNullOrEmpty(Model.SiteBannerImgs))*@
@*                                {*@
@*                                    <div class="dz-default dz-message"><span>此处显示正使用的Banner图片</span>*@
@*                                    </div>*@
@*                                }*@
@*                                else*@
@*                                {*@
@*                                    var imgList = Model.SiteBannerImgs.Split('|');*@
@*                                    foreach (string imgUrl in imgList)*@
@*                                    {*@
@*                                        <div class="dz-preview dz-image-preview">  *@
@*                                            <div class="dz-image">*@
@*                                                <img data-dz-thumbnail="" alt="@imgUrl" src="@imgUrl">*@
@*                                            </div>          *@
@*                                            <a href="javascript:;"  class="uploadDelete btn red btn-sm btn-block">移除</a>*@
@*                                        </div>*@
@*                                    }*@
@*                                }*@
@*                                *@
@*                            </div>*@
@*                            @using (Html.BeginForm("SaveBanner", "Seo", FormMethod.Post, new {@class = "dropzone", id = "dropzoneContainer",enctype="multipart/form-data"}))*@
@*                            {*@
@*                                @Html.AntiForgeryToken()*@
@*                                @Html.HiddenFor(s => s.Id)*@
@*                            }*@
@**@
@*                            <div class="margin-top-10">*@
@*                                <button type="submit" id="saveBanner" class="btn green">上传图片</button>*@
@*                            </div>*@
@*                        </div>*@
@*                        <!-- END Upload Banner TAB -->*@
                        <!-- Watermark TAB -->
                        <div class="tab-pane" id="tab_1_2">
                            <form id="watermarkForm" postUrl="/admin/seo/savewatermark">
                                <div class="form-group">
                                    <label class="control-label">是否启用图片上传添加水印</label><br />
                                    <input type="checkbox" id="watermarkState" class="make-switch" @checkState data-on-color="success" data-off-color="danger">
                                </div>
                                <div class="form-group">
                                    <label class="control-label">水印名称</label>
                                    @Html.TextBoxFor(s => s.Watermark, new { @class = "form-control", placeholder = "填写水印名称" })
                                </div>
                                <div class="margin-top-10">
                                    <button type="submit" id="saveWaterMark" class="btn green">保存设置</button>
                                </div>
                            </form>
                        </div>
                        <!-- END Watermark TAB -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section PageLevelScriptsPlugins
{
@*    @Scripts.Render("~/assets/global/dropzone/scripts")*@
@*    <script src="/Content/assets/pages/scripts/form-dropzone.js" type="text/javascript"></script>*@

}


@section PageCustomScripts
{
    <script type="text/javascript">
        
        $(function () {
            initValidate("siteSettingForm");
            initValidate("watermarkForm");

        });


        function initValidate(formId) {
            var postUrl = $("#" + formId).attr("postUrl");
            $("#" + formId).validate({
                errorElement: 'span', //default input error message container
                errorClass: 'help-block', // default input error message class
                onsubmit: true,
                onfocusout: false,
                onkeyup: false,

                rules: { //规则
                    SiteTitle: {
                        required: true,
                        maxlength: 50
                    }
                },
                messages: { //验证错误信息
                    SiteTitle: {
                        required: "请输入网站名称",
                        minlength: "网站名称限制在50个字符以内"
                    }
                },
                highlight: function (element) { // hightlight error inputs
                    $(element)
                        .closest('.form-group').addClass('has-error'); // set error class to the control group
                },

                submitHandler: function (form) { //通过之后回调

                    //进行ajax传值
                    var editModel = null;

                    switch (formId) {
                    case "siteSettingForm":
                        editModel = {
                            Id: $('#Id').val().trim(),
                            SiteTitle: $("#SiteTitle").val().trim(),
                            SiteKeywords: $("#SiteKeywords").val().trim(),
                            SiteDescription: $('#SiteDescription').val().trim(),
                            IcpNumber: $("#IcpNumber").val().trim()
                        };
                        break;
                    case "watermarkForm":
                        if ($("#watermarkState").bootstrapSwitch('state')) {
                            var mark = $("#Watermark").val().trim();
                            if (mark.length == 0) {
                                UIBootstrapGrowl.show('body', '开启水印后，应填写水印内容', 'danger');
                                break;
                            }
                        }
                        editModel = {
                            Id: $('#Id').val().trim(),
                            SiteTitle: "TitleTemp",
                            WatermarkAble: $("#watermarkState").bootstrapSwitch('state'),
                            Watermark: $("#Watermark").val().trim()
                        };
                        break;
                    }
                    if (editModel == null) {
                        return false;
                    }

                    abp.ajax({
                        url: postUrl,
                        data: JSON.stringify(editModel)
                    }).done(function (data) {
                        //要执行的代码
                        if (data.success == true) {
                            UIBootstrapGrowl.show('body', '保存成功', 'success');
                            setTimeout(function () { location.reload() }, 2000);
                        } else {
                            UIBootstrapGrowl.show('body', '保存失败，请联系技术人员', 'warning');
                        }
                    });
                },
                invalidHandler: function (form, validator) { return false; }
            });
        }

    </script>
}