CarFactory.Web/Controllers/AboutController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using CarFactory.Application.Company;
using CarFactory.Application.Company.Dtos;
using CarFactory.Application.Seo;
using CarFactory.Core.CustomDomain.Company;

namespace CarFactory.Web.Controllers
{
    public class AboutController : CarFactoryControllerBase
    {
        private readonly ICompanyAppService _companyAppService;
        

        public AboutController(ISeoAppService seoAppService, ICompanyAppService companyAppService):base(seoAppService)
        {
            _companyAppService = companyAppService;
        }
        public ActionResult Index()
        {
            CompanyListDto info = _companyAppService.GetDefaultCompanyAsync().Result;
            ViewBag.SeoSetting = GetSeoSetting();

            return View(info);
        }

        public async Task<ActionResult> Contact()
        {
            CompanyListDto info = await _companyAppService.GetDefaultCompanyAsync();
            ViewBag.SeoSetting = GetSeoSetting();

            return View(info);
        }
	}
}

CarFactory.Web/Controllers/ProductController.cs
using Abp.Application.Services.Dto;
using CarFactory.Application.Category;
using CarFactory.Application.Category.Dtos;
using CarFactory.Application.Products;
using CarFactory.Application.Products.Dtos;
using CarFactory.Web.Models.Common;
using System.Linq;
using System.Web.Mvc;
using CarFactory.Application.Seo;
using X.PagedList;

namespace CarFactory.Web.Controllers
{
    public class ProductController : CarFactoryControllerBase
    {
        private readonly IProductAppService _productAppService;

        private readonly ICategoryAppService _categoryAppService;


        public ProductController(ISeoAppService seoAppService, IProductAppService productAppService,ICategoryAppService categoryAppService):base(seoAppService)
        {
            _productAppService = productAppService;
            _categoryAppService = categoryAppService;
        }


        public ActionResult List(int? page, string shortName = "")
        {
            CategoryListDto activeCategory = null;
            int pageIndex = ((page != null && page.Value >= 1) ? page.Value : 1) - 1;

            var categoryList = _categoryAppService.GetCategorysOnShowAsync().Result;
            activeCategory = categoryList.FirstOrDefault();
            ViewBag.ActiveCategory = activeCategory;

            if (!string.IsNullOrEmpty(shortName))
            {
                var tempCategory = categoryList.FirstOrDefault(c => c.ShortName == shortName);
                if (tempCategory != null)
                {
                    ViewBag.ActiveCategory = tempCategory;
                    activeCategory = tempCategory;
                }
            }

            GetProductInput pagedInput = new GetProductInput()
            {
                CategoryId = activeCategory.Id,
                Sorting = "CreationTime"
            };
            pagedInput.SkipCount = pageIndex * pagedInput.MaxResultCount;

            var products = _productAppService.GetPagedProductsAsync(pagedInput).Result;

            var pagedProducts = new StaticPagedList<ProductListDto>(products.Items, pageIndex + 1, pagedInput.MaxResultCount,
                products.TotalCount);

            ViewBag.SeoSetting = GetSeoSetting();

            return View(pagedProducts);
        }

        // GET: Product
        public ActionResult Detail(int id = 0)
        {
            EntityDto<int> input = new EntityDto<int>(){Id = id};
            PreAndNextNavModel<ProductListDto> dtoNavModel = new PreAndNextNavModel<ProductListDto>();

            var currentDto = _productAppService.GetProductByIdAsync(input).Result;

            if (currentDto != null)
            {
                dtoNavModel.CurrentItem = currentDto;
                var preDto = _productAppService.GetFirstOrDefaultAsync(p => p.CreationTime < currentDto.CreationTime && p.CategoryId==currentDto.CategoryId
                ,r => r.CreationTime, false).Result;

                var nextDto = _productAppService.GetFirstOrDefaultAsync(p => p.CreationTime > currentDto.CreationTime && p.CategoryId == currentDto.CategoryId,
                    r => r.CreationTime, true).Result;
                dtoNavModel.PreviousItem = preDto;
                dtoNavModel.NextItem = nextDto;
            }


            ViewBag.SeoSetting = GetSeoSetting();

            return View(dtoNavModel);
        }
    }
}

CarFactory.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Abp.Application.Services.Dto;
using CarFactory.Application.Products.Dtos;
using CarFactory.Application.Report;
using CarFactory.Application.Report.Dtos;
using CarFactory.Application.Seo;
using CarFactory.Web.Models.Common;
using X.PagedList;

namespace CarFactory.Web.Controllers
{
    public class ReportController : CarFactoryControllerBase
    {

        private readonly IReportAppService _reportAppService;

        public ReportController(IReportAppService reportAppService, ISeoAppService seoAppService):base(seoAppService)
        {
            _reportAppService = reportAppService;
        }


        // GET: Qualification
        public ActionResult List(int? page)
        {
            int pageIndex = ((page != null && page.Value >= 1) ? page.Value : 1) - 1;


            GetReportInput pagedInput = new GetReportInput();

            pagedInput.SkipCount = pageIndex * pagedInput.MaxResultCount;

            var reports = _reportAppService.GetPagedReportsAsync(pagedInput).Result;

            var pagedReports = new StaticPagedList<ReportListDto>(reports.Items, pageIndex + 1, pagedInput.MaxResultCount,
                reports.TotalCount);
            ViewBag.SeoSetting = GetSeoSetting();

            return View(pagedReports);
        }

        public ActionResult Detail(int id = 0)
        {
            EntityDto<int> input = new EntityDto<int>() { Id = id };
            PreAndNextNavModel<ReportListDto> dtoNavModel = new PreAndNextNavModel<ReportListDto>();

            var currentDto = _reportAppService.GetReportByIdAsync(input).Result;

            if (currentDto != null)
            {
                dtoNavModel.CurrentItem = currentDto;
                var preDto = _reportAppService.GetFirstOrDefaultAsync(p => p.CreationTime < currentDto.CreationTime,
                        r => r.CreationTime, false).Result;

                var nextDto = _reportAppService.GetFirstOrDefaultAsync(p => p.CreationTime > currentDto.CreationTime,
                        r => r.CreationTime, true).Result;

                dtoNavModel.PreviousItem = preDto;
                dtoNavModel.NextItem = nextDto;
            }

            ViewBag.SeoSetting = GetSeoSetting();


            return View(dtoNavModel);
        }

    }
}

CarFactory.Web/Views/Shared/PartialPages/_PartialCategoryList.cshtml
@model CarFactory.Web.Models.Layout.RightSideCategoryNavViewModel

<ul id="categoryList">
    @foreach (var dto in Model.CategoryMenu)
    {
        <li>
            @Html.ActionLink(dto.CategoryName,"List","Product",new {shortName = dto.ShortName},new{id = dto.ShortName})
        </li>
    }
</ul>

CarFactory.Web/Views/Shared/PartialPages/_PartialFooter.cshtml
@model CarFactory.Application.Company.Dtos.CompanyListDto
<div class="foot">
    <div class="footer">
        <div class="b_nav">
            <ul>
                <li style="background:none;"><a href="/">网站首页</a></li>

                <li>@Html.ActionLink("关于我们", "Index", "About", null, new { rel = "nofollow" })</li>

                <li><a href='/product'>产品展示</a></li>

                <li>@Html.ActionLink("检测报告", "List", "Report", null, new { rel = "nofollow" })</li>

                <li>@Html.ActionLink("联系我们", "Contact", "About", null, new { rel = "nofollow" })</li>

            </ul>
        </div>
        <div class="fo">
            <p>Copyright &copy;@Model.CompanyName 版权所有 网站备案号：鲁ICP备15045413号</p>
            <p>地址：@Model.Address  联系我们：@Model.Tel     <a href="http://www.ytaochang.com/sitemap.html">网站地图</a><a href="http://www.ytaochang.com/sitemap.xml"> XML</a></p>
        </div>
    </div>
</div>

CarFactory.Web/Views/Shared/PartialPages/_PartialHeader.cshtml
<div class="nav">
    <ul>
        <li style="background: none;"><a href="/" rel="nofollow">网站首页</a></li>

        <li>@Html.ActionLink("关于我们", "Index", "About", null, new { rel = "nofollow" })</li>

        <li><a href="/product" rel="nofollow">产品展示</a></li>

        <li>@Html.ActionLink("检测报告", "List", "Report", null, new { rel = "nofollow" })</li>

        <li>@Html.ActionLink("联系我们", "Contact", "About", null, new { rel = "nofollow" })</li>

    </ul>
</div>